uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Push Docker image to Container Registry
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker tag Docker_Github__cicd- ${{ secrets.DOCKERHUB_USERNAME }}/Docker_Github__cicd-:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/Docker_Github__cicd-:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Docker
      run: |
        echo "Deployment steps go here..."
